-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_REGIONS (
--   	REGIONID INT PRIMARY KEY,
--     REGIONDESCRIPTION VARCHAR(50) NOT NULL
-- ) AS
-- SELECT 
--   DISTINCT REGIONID,
--   TRIM(REGIONDESCRIPTION) AS REGIONDESCRIPTION
-- FROM {{ source('sources', 'regions') }}
-- WHERE REGIONID IS NOT NULL

select
  DISTINCT REGIONID,
  TRIM(REGIONDESCRIPTION) AS REGIONDESCRIPTION
from
    {{ source('sources', 'regions') }}
WHERE REGIONID IS NOT NULL