-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_PRODUCTS (
-- 	PRODUCTID INT PRIMARY KEY,
--     PRODUCTNAME VARCHAR(40) NOT NULL,
--     SUPPLIERID INT,
--     CATEGORYID INT,
--     QUANTITYPERUNIT VARCHAR(20),
--     UNITPRICE NUMERIC(10, 2),
--     UNITSINSTOCK SMALLINT,
--     UNITSONORDER SMALLINT,
--     REORDERLEVEL SMALLINT,
--     DISCONTINUED BOOLEAN NOT NULL
-- ) AS
-- SELECT 
--   DISTINCT PRODUCTID,
--   TRIM(PRODUCTNAME) AS PRODUCTNAME,
--   SUPPLIERID,
--   CATEGORYID,
--   TRIM(QUANTITYPERUNIT) AS QUANTITYPERUNIT,
--   TRY_CAST(UNITPRICE AS FLOAT) AS UNITPRICE,
--   TRY_CAST(UNITSINSTOCK AS INTEGER) AS UNITSINSTOCK,
--   TRY_CAST(UNITSONORDER AS INTEGER) AS UNITSONORDER,
--   TRY_CAST(REORDERLEVEL AS INTEGER) AS REORDERLEVEL,
--   TRY_CAST(DISCONTINUED AS INTEGER) AS DISCONTINUED
-- FROM {{ source('sources', 'products') }}
-- WHERE PRODUCTID IS NOT NULL

select
  DISTINCT PRODUCTID,
  TRIM(PRODUCTNAME) AS PRODUCTNAME,
  SUPPLIERID,
  CATEGORYID,
  TRIM(QUANTITYPERUNIT) AS QUANTITYPERUNIT,
  TRY_CAST(UNITPRICE AS FLOAT) AS UNITPRICE,
  TRY_CAST(UNITSINSTOCK AS INTEGER) AS UNITSINSTOCK,
  TRY_CAST(UNITSONORDER AS INTEGER) AS UNITSONORDER,
  TRY_CAST(REORDERLEVEL AS INTEGER) AS REORDERLEVEL,
  TRY_CAST(DISCONTINUED AS INTEGER) AS DISCONTINUED
from
    {{ source('sources', 'products') }}
WHERE PRODUCTID IS NOT NULL