-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_ORDERS (
-- 	ORDERID INT PRIMARY KEY,
--     CUSTOMERID VARCHAR,
--     EMPLOYEEID INT,
--     ORDERDATE DATE,
--     REQUIREDDATE DATE,
--     SHIPPEDDATE DATE,
--     SHIPVIA INT,
--     FREIGHT NUMERIC(10, 2),
--     SHIPNAME VARCHAR(40),
--     SHIPADDRESS VARCHAR(60),
--     SHIPCITY VARCHAR(15),
--     SHIPREGION VARCHAR(15),
--     SHIPPOSTALCODE VARCHAR(10),
--     SHIPCOUNTRY VARCHAR(15)
-- ) AS
-- SELECT 
--   DISTINCT ORDERID,
--   TRIM(CUSTOMERID) AS CUSTOMERID,
--   EMPLOYEEID,
--   TRY_TO_DATE(ORDERDATE, 'YYYY-MM-DD') AS ORDERDATE,
--   TRY_TO_DATE(REQUIREDDATE, 'YYYY-MM-DD') AS REQUIREDDATE,
--   TRY_TO_DATE(SHIPPEDDATE, 'YYYY-MM-DD') AS SHIPPEDDATE,
--   SHIPVIA,
--   TRY_CAST(FREIGHT AS FLOAT) AS FREIGHT,
--   TRIM(SHIPNAME) AS SHIPNAME,
--   TRIM(SHIPADDRESS) AS SHIPADDRESS,
--   TRIM(SHIPCITY) AS SHIPCITY,
--   TRIM(SHIPREGION) AS SHIPREGION,
--   TRIM(SHIPPOSTALCODE) AS SHIPPOSTALCODE,
--   TRIM(SHIPCOUNTRY) AS SHIPCOUNTRY
-- FROM {{ source('sources', 'orders') }}
-- WHERE ORDERID IS NOT NULL

select
  DISTINCT ORDERID,
  TRIM(CUSTOMERID) AS CUSTOMERID,
  EMPLOYEEID,
  TRY_TO_DATE(ORDERDATE, 'YYYY-MM-DD') AS ORDERDATE,
  TRY_TO_DATE(REQUIREDDATE, 'YYYY-MM-DD') AS REQUIREDDATE,
  TRY_TO_DATE(SHIPPEDDATE, 'YYYY-MM-DD') AS SHIPPEDDATE,
  SHIPVIA,
  TRY_CAST(FREIGHT AS FLOAT) AS FREIGHT,
  TRIM(SHIPNAME) AS SHIPNAME,
  TRIM(SHIPADDRESS) AS SHIPADDRESS,
  TRIM(SHIPCITY) AS SHIPCITY,
  TRIM(SHIPREGION) AS SHIPREGION,
  TRIM(SHIPPOSTALCODE) AS SHIPPOSTALCODE,
  TRIM(SHIPCOUNTRY) AS SHIPCOUNTRY
from
    {{ source('sources', 'orders') }}
WHERE ORDERID IS NOT NULL