-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_TERRITORIES (
-- 	TERRITORYID INT PRIMARY KEY,
--     TERRITORYDESCRIPTION VARCHAR(50) NOT NULL,
--     REGIONID INT NOT NULL
-- ) AS
-- SELECT 
--   DISTINCT TERRITORYID,
--   TRIM(TERRITORYDESCRIPTION) AS TERRITORYDESCRIPTION,
--   REGIONID
-- FROM {{ source('sources', 'territories') }}
-- WHERE TERRITORYID IS NOT NULL
-- ORDER BY 3 ASC

select
  DISTINCT TERRITORYID,
  TRIM(TERRITORYDESCRIPTION) AS TERRITORYDESCRIPTION,
  REGIONID
from
    {{ source('sources', 'territories') }}
WHERE TERRITORYID IS NOT NULL
ORDER BY 3 ASC