SELECT
  DISTINCT ORDERID,
  TRIM(CUSTOMERID) AS CUSTOMERID,
  EMPLOYEEID,
  TRY_TO_DATE(ORDERDATE, 'YYYY-MM-DD') AS ORDERDATE,
  TRY_TO_DATE(REQUIREDDATE, 'YYYY-MM-DD') AS REQUIREDDATE,
  TRY_TO_DATE(SHIPPEDDATE, 'YYYY-MM-DD') AS SHIPPEDDATE,
  SHIPVIA,
  TRY_CAST(FREIGHT AS FLOAT) AS FREIGHT,
  TRIM(SHIPNAME) AS SHIPNAME,
  TRIM(SHIPADDRESS) AS SHIPADDRESS,
  TRIM(SHIPCITY) AS SHIPCITY,
  TRIM(SHIPREGION) AS SHIPREGION,
  TRIM(SHIPPOSTALCODE) AS SHIPPOSTALCODE,
  TRIM(SHIPCOUNTRY) AS SHIPCOUNTRY
FROM
    {{ source('sources', 'orders') }}
WHERE ORDERID IS NOT NULL