-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_EMPLOYEE_TERRITORIES (
-- 	EMPLOYEEID INT NOT NULL,
--     TERRITORYID INT NOT NULL,
--     PRIMARY KEY (EMPLOYEEID, TERRITORYID)
-- ) AS 
-- SELECT 
--   TRIM(EMPLOYEEID) AS EMPLOYEEID ,
--   TRIM(TERRITORYID) AS TERRITORYID
-- FROM 
--     {{ source('sources', 'employee_territories') }}
-- WHERE EMPLOYEEID IS NOT NULL AND TERRITORYID IS NOT NULL

select
  TRIM(EMPLOYEEID) AS EMPLOYEEID ,
  TRIM(TERRITORYID) AS TERRITORYID
from
    {{ source('sources', 'employee_territories') }}
WHERE EMPLOYEEID IS NOT NULL AND TERRITORYID IS NOT NULL