-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_CUSTOMERS (
--     CUSTOMERID VARCHAR PRIMARY KEY,
--     COMPANYNAME VARCHAR(200),
--     CONTACTNAME VARCHAR(200),
--     CONTACTTITLE VARCHAR(200),
--     ADDRESS VARCHAR(200),
--     CITY VARCHAR(15),
--     REGION VARCHAR(15),
--     POSTALCODE VARCHAR(10),
--     COUNTRY VARCHAR(15),
--     PHONE VARCHAR(24),
--     FAX VARCHAR(24)
-- ) AS
-- SELECT 
--   DISTINCT CUSTOMERID,
--   TRIM(COMPANYNAME) AS COMPANYNAME,
--   COALESCE(LEFT(TRIM(CONTACTNAME), 200), 'UNKNOWN') AS CONTACTNAME,
--   LEFT(TRIM(CONTACTTITLE), 200) AS CONTACTTITLE,
--   LEFT(TRIM(ADDRESS), 200) AS ADDRESS,
--   LEFT(TRIM(CITY), 15) AS CITY,
--   COALESCE(LEFT(TRIM(REGION), 15), 'UNKNOWN') AS REGION,
--   LEFT(TRIM(POSTALCODE), 10) AS POSTALCODE,
--   LEFT(TRIM(COUNTRY), 15) AS COUNTRY,
--   REGEXP_REPLACE(LEFT(TRIM(PHONE), 24), '[^0-9]', '') AS PHONE,
--   REGEXP_REPLACE(LEFT(TRIM(FAX), 24), '[^0-9]', '') AS FAX
-- FROM 
--     {{ source('sources', 'customers') }}
-- WHERE CUSTOMERID IS NOT NULL AND COMPANYNAME IS NOT NULL

select
  DISTINCT CUSTOMERID,
  TRIM(COMPANYNAME) AS COMPANYNAME,
  COALESCE(LEFT(TRIM(CONTACTNAME), 200), 'UNKNOWN') AS CONTACTNAME,
  LEFT(TRIM(CONTACTTITLE), 200) AS CONTACTTITLE,
  LEFT(TRIM(ADDRESS), 200) AS ADDRESS,
  LEFT(TRIM(CITY), 15) AS CITY,
  COALESCE(LEFT(TRIM(REGION), 15), 'UNKNOWN') AS REGION,
  LEFT(TRIM(POSTALCODE), 10) AS POSTALCODE,
  LEFT(TRIM(COUNTRY), 15) AS COUNTRY,
  REGEXP_REPLACE(LEFT(TRIM(PHONE), 24), '[^0-9]', '') AS PHONE,
  REGEXP_REPLACE(LEFT(TRIM(FAX), 24), '[^0-9]', '') AS FAX    
from
    {{ source('sources', 'customers') }}
WHERE CUSTOMERID IS NOT NULL AND COMPANYNAME IS NOT NULL