-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_CATEGORIES AS 
-- SELECT * FROM (
--     SELECT 
--         DISTINCT CATEGORYID,
--         TRIM(CATEGORYNAME) AS CATEGORYNAME,
--         TRIM(DESCRIPTION) AS DESCRIPTION,
--         TO_BINARY(PICTURE, 'BASE64') AS PICTURE
--     FROM 
--         {{ source('sources', 'categories') }}
--     WHERE CATEGORYID IS NOT NULL
--       AND CATEGORYNAME IS NOT NULL
-- )

SELECT 
    DISTINCT CATEGORYID,
    TRIM(CATEGORYNAME) AS CATEGORYNAME,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    TO_BINARY(PICTURE, 'UTF-8') AS PICTURE
FROM {{ source('sources', 'categories') }}
WHERE CATEGORYID IS NOT NULL
    AND CATEGORYNAME IS NOT NULL