-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_SUPPLIERS (
-- 	SUPPLIERID INT PRIMARY KEY,
--     COMPANYNAME VARCHAR(40) NOT NULL,
--     CONTACTNAME VARCHAR(30),
--     CONTACTTITLE VARCHAR(30),
--     ADDRESS VARCHAR(60),
--     CITY VARCHAR(15),
--     REGION VARCHAR(15),
--     POSTALCODE VARCHAR(10),
--     COUNTRY VARCHAR(15),
--     PHONE VARCHAR(24),
--     FAX VARCHAR(24),
--     HOMEPAGE TEXT
-- ) AS
-- SELECT 
--   DISTINCT SUPPLIERID,
--   TRIM(COMPANYNAME) AS COMPANYNAME,
--   TRIM(CONTACTNAME) AS CONTACTNAME,
--   TRIM(CONTACTTITLE) AS CONTACTTITLE,
--   TRIM(ADDRESS) AS ADDRESS,
--   TRIM(CITY) AS CITY,
--   TRIM(REGION) AS REGION,
--   TRIM(POSTALCODE) AS POSTALCODE,
--   TRIM(COUNTRY) AS COUNTRY,
--   REGEXP_REPLACE(TRIM(PHONE), '[^0-9]', '') AS PHONE,
--   REGEXP_REPLACE(TRIM(FAX), '[^0-9]', '') AS FAX,
--   TRIM(HOMEPAGE) AS HOMEPAGE
-- FROM {{ source('sources', 'suppliers') }}
-- WHERE SUPPLIERID IS NOT NULL


select
  DISTINCT SUPPLIERID,
  TRIM(COMPANYNAME) AS COMPANYNAME,
  TRIM(CONTACTNAME) AS CONTACTNAME,
  TRIM(CONTACTTITLE) AS CONTACTTITLE,
  TRIM(ADDRESS) AS ADDRESS,
  TRIM(CITY) AS CITY,
  TRIM(REGION) AS REGION,
  TRIM(POSTALCODE) AS POSTALCODE,
  TRIM(COUNTRY) AS COUNTRY,
  REGEXP_REPLACE(TRIM(PHONE), '[^0-9]', '') AS PHONE,
  REGEXP_REPLACE(TRIM(FAX), '[^0-9]', '') AS FAX,
  TRIM(HOMEPAGE) AS HOMEPAGE
from
    {{ source('sources', 'suppliers') }}
WHERE SUPPLIERID IS NOT NULL