-- CREATE OR REPLACE TABLE ELT_PROJECT.RAW.RAW_EMPLOYEES (
-- 	EMPLOYEEID INT PRIMARY KEY,
--     LASTNAME VARCHAR(20) NOT NULL,
--     FIRSTNAME VARCHAR(10) NOT NULL,
--     TITLE VARCHAR(30),
--     TITLEOFCOURTESY VARCHAR(25),
--     BIRTHDATE DATE,
--     HIREDATE DATE,
--     ADDRESS VARCHAR(60),
--     CITY VARCHAR(15),
--     REGION VARCHAR(15),
--     POSTALCODE VARCHAR(10),
--     COUNTRY VARCHAR(15),
--     HOMEPHONE VARCHAR(24),
--     EXTENSION VARCHAR(4),
--     PHOTO BINARY,
--     NOTES TEXT,
--     REPORTSTO INT,
--     PHOTOPATH VARCHAR(255)
-- ) AS 
-- SELECT 
--   DISTINCT EMPLOYEEID,
--   TRIM(LASTNAME) AS LASTNAME,
--   TRIM(FIRSTNAME) AS FIRSTNAME,
--   TRIM(TITLE) AS TITLE,
--   TRIM(TITLEOFCOURTESY) AS TITLEOFCOURTESY,
--   TRIM(BIRTHDATE) AS BIRTHDATE,
--   TRIM(HIREDATE) AS HIREDATE,
--   TRIM(ADDRESS) AS ADDRESS,
--   TRIM(CITY) AS CITY,
--   TRIM(REGION) AS REGION,
--   TRIM(POSTALCODE) AS POSTALCODE,
--   TRIM(COUNTRY) AS COUNTRY,
--   REGEXP_REPLACE(TRIM(HOMEPHONE), '[^0-9]', '') AS HOMEPHONE,
--   TRIM(EXTENSION) AS EXTENSION,
--   TO_BINARY(PHOTO, 'BASE64') AS PHOTO,
--   TRIM(NOTES) AS NOTES,
--   COALESCE(TRIM(REPORTSTO), '0') AS REPORTSTO,
--   TRIM(PHOTOPATH) AS PHOTOPATH
-- FROM 
--     {{ source('sources', 'employees') }}
-- WHERE EMPLOYEEID IS NOT NULL


select
  DISTINCT EMPLOYEEID,
  TRIM(LASTNAME) AS LASTNAME,
  TRIM(FIRSTNAME) AS FIRSTNAME,
  TRIM(TITLE) AS TITLE,
  TRIM(TITLEOFCOURTESY) AS TITLEOFCOURTESY,
  TRIM(BIRTHDATE) AS BIRTHDATE,
  TRIM(HIREDATE) AS HIREDATE,
  TRIM(ADDRESS) AS ADDRESS,
  TRIM(CITY) AS CITY,
  TRIM(REGION) AS REGION,
  TRIM(POSTALCODE) AS POSTALCODE,
  TRIM(COUNTRY) AS COUNTRY,
  REGEXP_REPLACE(TRIM(HOMEPHONE), '[^0-9]', '') AS HOMEPHONE,
  TRIM(EXTENSION) AS EXTENSION,
  TO_BINARY(PHOTO, 'BASE64') AS PHOTO,
  TRIM(NOTES) AS NOTES,
  COALESCE(TRIM(REPORTSTO), '0') AS REPORTSTO,
  TRIM(PHOTOPATH) AS PHOTOPATH
from
    {{ source('sources', 'employees') }}
WHERE EMPLOYEEID IS NOT NULL