version: 2

models:
  - name: raw_categories
    description: "Trasformed model for raw_categories"
    columns:
      - name: category_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: raw_customers
    description: "Trasformed model for raw_customers"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null